name: Docker Image CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login Docker Registry
      run: docker login -u ${{ secrets.RegistryUsername }} -p ${{ secrets.RegistryPassword }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag a1tan/sampleapp:pull-$GITHUB_SHA
    - name: Push the Docker image
      run: docker push a1tan/sampleapp:pull-$GITHUB_SHA
